JUMPING		= False
ROTATING	= False
STORE		= False
SCROLL_SPEED= 0.1
CURRENT_WALL= 0
CAN_JUMP	= True
CAN_LEFT	= True
CAN_RIGHT	= True
CAN_ROLL	= True
ROLLING 	= False
SONG_VOLUME	= 0#.7
FX_VOLUME	= 1
INVENTORY   = False
INVENTORY_FULL = False
INVINCIBLE = False
MAGNET_ACTIVE = False
APPLE_MODE = False
MAIN_MENU = True

# Camera
SHAKING		= False

# Game status
GAME_OVER	= False
CURR_EFFECT = None
